name: paneuc-post
channels:
  - bioconda
  - defaults
dependencies:
  - python
  - snakemake
  - bcftools
  - bedtools
  - pynvim
  - git-annex
  - r
  - r-tidyverse
  - r-remotes
  - jupytext
  - scikit-allel
